name: lgss-unifi
adopt-info: unifi
summary: Unifi Network controller software.
description: |
  Unofficial snap package of the Unifi Network Application software.

  Ubiquiti UniFi server is a centralized management system for UniFi suite of
  devices. After the UniFi server is installed, the UniFi Network application
  can be accessed on any web browser. The UniFi Network application allows the
  operator to instantly provision thousands of UniFi devices, map out network
  topology, quickly manage system traffic, and further provision individual
  UniFi devices.
base: core24
confinement: strict
grade: stable
platforms:
  amd64:
  arm64:

package-repositories:
  - type: apt
    components: [ubiquiti]
    suites: [stable]
    key-id: 4A228B2D358A5094178285BE06E85760C0A52C50
    url: https://www.ui.com/downloads/unifi/debian

  - type: apt
    components: [multiverse]
    suites: [noble/mongodb-org/8.0]
    key-id: 4B0752C1BCA238C0B4EE14DC41DE058A4E7DCA05
    url: https://repo.mongodb.org/apt/ubuntu

layout:
   /usr/lib/unifi/bin:
     bind: $SNAP/usr/lib/unifi/bin
   /usr/lib/unifi/conf:
     bind: $SNAP/usr/lib/unifi/conf
   /usr/lib/unifi/dl:
     bind: $SNAP/usr/lib/unifi/dl
   /usr/lib/unifi/lib:
     bind: $SNAP/usr/lib/unifi/lib
   /usr/lib/unifi/webapps:
     bind: $SNAP/usr/lib/unifi/webapps
   /usr/lib/unifi/data:
     bind: $SNAP_DATA/data
   /usr/lib/unifi/run:
     bind: $SNAP_DATA/run
   /usr/lib/unifi/logs:
     bind: $SNAP_DATA/logs
   /usr/lib/unifi/work:
     bind: $SNAP_DATA/work

apps:
  unifi:
    command: bin/launcher.sh
    daemon: simple
    plugs:
      - mount-observe
      - network
      - network-bind
      - network-observe

parts:
  unifi:
    plugin: nil
    build-packages:
      - ca-certificates-java
    stage-packages:
      - openjdk-17-jre-headless
      - unifi
    override-build: |
      snapcraftctl build
      VER="$(cat $SNAPCRAFT_PART_INSTALL/usr/lib/unifi/webapps/ROOT/app-unifi/.version | \
           sed 's/-.*$//')"
      snapcraftctl set-version $VER
    override-prime: |
      snapcraftctl prime
      ln -sf /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/bin/mongod \
        $SNAPCRAFT_PRIME/usr/lib/unifi/bin/mongod
  scripts:
    plugin: dump
    source: scripts
    organize:
      launcher.sh: bin/launcher.sh
